const div1 = document.getElementById("div1");
const body = document.body;
console.dir(document);
body.style.backgroundColor = "lightblue";
let clicked = false;
const par = document.createElement("p");
par.innerText = "This is a paragraph generated by JS";
function changecolor() {
    if (clicked == false) {
        document.getElementById("head1").innerText = "Heading Changed";
        document.getElementById("btn1").innerText = "I am Clicked";
        body.style.backgroundColor = "pink";
        clicked = true;
        div1.appendChild(par);
    } else {
        document.getElementById("head1").innerText = "This is Heading";
        document.getElementById("btn1").innerText = "Click Me";
        body.style.backgroundColor = "lightblue";
        clicked = false;
    }
}
let color = false
document.getElementById("head1").addEventListener("click", () => {
    if (color == false) {
        document.getElementById("head1").style.backgroundColor = "red";
        color = true
    } else {
        document.getElementById("head1").style.backgroundColor = "yellow";
        color = false
    }
});
let count = 0;
document.getElementById("para1").addEventListener("click", () => {
    const color = ["red", "blue", "green", "yellow", "purple", "pink", "orange"];
    document.getElementById("para1").style.backgroundColor = color[count];
    count = count + 1;
    if(count>7){
        count = 0;
    }
})
function onsubmit1() {
    const table = document.createElement('table');
    const thead = document.createElement('thead');
    const tbody = document.createElement('tbody');
    table.appendChild(thead);
    table.appendChild(tbody);

    // Get input values
    const name = document.getElementById("name").value;
    const email = document.getElementById("email").value;
    const age = document.getElementById("age").value;

    // Create header row
    const headerRow = document.createElement('tr');
    const headers = ['Name', 'Age', 'Email'];
    headers.forEach(headerText => {
        const th = document.createElement('th');
        th.textContent = headerText;
        headerRow.appendChild(th);
    });
    thead.appendChild(headerRow);

    // Create data row
    const dataRow = document.createElement('tr');
    const data = [name, age, email];
    data.forEach(item => {
        const cell = document.createElement('td');
        cell.textContent = item;
        dataRow.appendChild(cell);
    });
    tbody.appendChild(dataRow);

    // Append the table to #data div
    document.getElementById('data').appendChild(table);
}
